---
#persistent volume

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv
#   namespace: java
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
  
# ---
#persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: java
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
#mysql deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: java
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:8
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: test@123
          - name: MYSQL_DATABASE
            value: "bankappdb"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes: 
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc


        

---
#mysql-service

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: java
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
--- 
#bank-app deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deployment
  namespace: java
spec:
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp-container
        image: rahul6364/bank-app:latest
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql-service:3306/bankappdb
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: test@123
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: update
          - name: SERVER_ADDRESS
            value: 0.0.0.0
          - name: SERVER_PORT
            value: "8081"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3

        ports:
        - containerPort: 8081
          name: bankapp
---
#bank-app service
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: java
spec:
  selector:
    app: bankapp
  ports:
  - port: 8081
    targetPort: 8081
  type: LoadBalancer
---
